#ifndef ISHIZUE_VERSION_H
#define ISHIZUE_VERSION_H

#define ISHIZUE_VERSION_MAJOR 1
#define ISHIZUE_VERSION_MINOR 0
#define ISHIZUE_VERSION_PATCH 0

#define ISHIZUE_VERSION_STRING "1.0.0"

#define ISHIZUE_VERSION \
    ((ISHIZUE_VERSION_MAJOR << 16) | \
     (ISHIZUE_VERSION_MINOR <<  8) | \
     (ISHIZUE_VERSION_PATCH))

#endif
